/analysis/Enable
/PolarimeterStudies/detector/left 0
/PolarimeterStudies/detector/support 0
/PolarimeterStudies/detector/armlength 15 cm
/PolarimeterStudies/detector/armangle 0
/PolarimeterStudies/target/x 2 cm
/PolarimeterStudies/target/z 5 mm
/PolarimeterStudies/detector/nx 1
/PolarimeterStudies/detector/ny 1
/gun/particle deuteron
/gun/position 0 0 -20 cm
/gun/direction 0 0 1
/PolarimeterStudies/detector/update
/process/inactivate dInelastic
/control/foreach scripts/E22EnergyLossInTarget/Thickness.mac Ekin "100 150 200 250 270"