/analysis/Enable
/gun/position 0 0 -30 cm
/gun/particle deuteron
/gun/direction 0 0 1
/PolarimeterStudies/generator/setGenerator gun
/gun/energy 100 MeV
/analysis/setFileName 100.root
/run/beamOn 1000
/gun/energy 150 MeV
/analysis/setFileName 150.root
/run/beamOn 1000
/gun/energy 200 MeV
/analysis/setFileName 200.root
/run/beamOn 1000
/gun/energy 250 MeV
/analysis/setFileName 250.root
/run/beamOn 1000
/gun/energy 270 MeV
/analysis/setFileName 270.root
/run/beamOn 1000