/PolarimeterStudies/detector/scenario calibration
/run/initialize
/jedi/elastic/theta_min 2 deg
/jedi/elastic/theta_max 10 deg
/analysis/Enable
/PolarimeterStudies/generator/setGenerator beam
/PolarimeterStudies/beam/position 0 0 -75 cm
/PolarimeterStudies/beam/spotsize 2.5 3 0 mm
/PolarimeterStudies/detector/targetSizeXY 50 mm
/control/alias thickness 5
/PolarimeterStudies/detector/update
/control/execute scripts/Testbeam2016bEnergyCalibration/material.mac

/control/alias material G4_C
/control/alias thickness 10
/control/execute scripts/Testbeam2016bEnergyCalibration/energy.mac
