/PolarimeterStudies/detector/scenario calibration
/run/initialize
/particle/select deuteron
/particle/process/inactivate 3
/particle/process/inactivate 4
/particle/process/inactivate 5
/jedi/elastic/theta_min 2 deg
/jedi/elastic/theta_max 10 deg
/analysis/Enable
/PolarimeterStudies/generator/setGenerator beam
/PolarimeterStudies/beam/position 0 0 -75 cm
/PolarimeterStudies/beam/spotsize 2.5 3 0 mm
/PolarimeterStudies/detector/targetSizeXY 50 mm
/PolarimeterStudies/detector/angle 0 deg
/control/alias thickness 5
/PolarimeterStudies/detector/update
/control/execute scripts/TestBeam2016BEnergyCalibration/material.mac

/control/alias material G4_GRAPHITE
/control/alias thickness 10
/control/execute scripts/TestBeam2016BEnergyCalibration/energy.mac

/PolarimeterStudies/detector/target 0
#Set target material even if not build because setFileName expects values
/control/alias material G4_AIR
/control/alias thickness 5
/control/execute scripts/TestBeam2016BEnergyCalibration/energy.mac