/PolarimeterStudies/target/z 5 mm 
/PolarimeterStudies/detector/update

/analysis/setFileName 100-5-0.root
/PolarimeterStudies/dcelastic/beamsize 0.010 0.010 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 0.500 mm
/PolarimeterStudies/dcelastic/energy 136.812 MeV
/run/beamOn {nevents}

/analysis/setFileName 100-5-1.root
/PolarimeterStudies/dcelastic/beamsize 0.033 0.033 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 1.500 mm
/PolarimeterStudies/dcelastic/energy 112.546 MeV
/run/beamOn {nevents}

/analysis/setFileName 100-5-2.root
/PolarimeterStudies/dcelastic/beamsize 0.062 0.062 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 2.500 mm
/PolarimeterStudies/dcelastic/energy 94.306 MeV
/run/beamOn {nevents}

/analysis/setFileName 100-5-3.root
/PolarimeterStudies/dcelastic/beamsize 0.097 0.097 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 3.500 mm
/PolarimeterStudies/dcelastic/energy 80.739 MeV
/run/beamOn {nevents}

/analysis/setFileName 100-5-4.root
/PolarimeterStudies/dcelastic/beamsize 0.139 0.139 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 4.500 mm
/PolarimeterStudies/dcelastic/energy 70.488 MeV
/run/beamOn {nevents}

