/PolarimeterStudies/target/z 20 mm 
/PolarimeterStudies/detector/update

/analysis/setFileName 100-20-0.0.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 0.100 mm
/PolarimeterStudies/dcelastic/energy 98.065 MeV
/run/beamOn {nevents}

/analysis/setFileName 100-20-0.2.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 0.300 mm
/PolarimeterStudies/dcelastic/energy 96.675 MeV
/run/beamOn {nevents}

/analysis/setFileName 100-20-0.4.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 0.500 mm
/PolarimeterStudies/dcelastic/energy 95.323 MeV
/run/beamOn {nevents}

/analysis/setFileName 100-20-0.6.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 0.700 mm
/PolarimeterStudies/dcelastic/energy 94.007 MeV
/run/beamOn {nevents}

/analysis/setFileName 100-20-0.8.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 0.900 mm
/PolarimeterStudies/dcelastic/energy 92.722 MeV
/run/beamOn {nevents}

/analysis/setFileName 100-20-1.0.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 1.100 mm
/PolarimeterStudies/dcelastic/energy 91.466 MeV
/run/beamOn {nevents}

/analysis/setFileName 100-20-1.2.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 1.300 mm
/PolarimeterStudies/dcelastic/energy 90.236 MeV
/run/beamOn {nevents}

/analysis/setFileName 100-20-1.4.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 1.500 mm
/PolarimeterStudies/dcelastic/energy 89.029 MeV
/run/beamOn {nevents}

/analysis/setFileName 100-20-1.6.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 1.700 mm
/PolarimeterStudies/dcelastic/energy 87.842 MeV
/run/beamOn {nevents}

/analysis/setFileName 100-20-1.8.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 1.900 mm
/PolarimeterStudies/dcelastic/energy 86.671 MeV
/run/beamOn {nevents}

/analysis/setFileName 100-20-2.0.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 2.100 mm
/PolarimeterStudies/dcelastic/energy 85.515 MeV
/run/beamOn {nevents}

/analysis/setFileName 100-20-2.2.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 2.300 mm
/PolarimeterStudies/dcelastic/energy 84.368 MeV
/run/beamOn {nevents}

/analysis/setFileName 100-20-2.4.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 2.500 mm
/PolarimeterStudies/dcelastic/energy 83.230 MeV
/run/beamOn {nevents}

/analysis/setFileName 100-20-2.6.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 2.700 mm
/PolarimeterStudies/dcelastic/energy 82.096 MeV
/run/beamOn {nevents}

/analysis/setFileName 100-20-2.8.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 2.900 mm
/PolarimeterStudies/dcelastic/energy 80.963 MeV
/run/beamOn {nevents}

/analysis/setFileName 100-20-3.0.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 3.100 mm
/PolarimeterStudies/dcelastic/energy 79.830 MeV
/run/beamOn {nevents}

/analysis/setFileName 100-20-3.2.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 3.300 mm
/PolarimeterStudies/dcelastic/energy 78.691 MeV
/run/beamOn {nevents}

/analysis/setFileName 100-20-3.4.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 3.500 mm
/PolarimeterStudies/dcelastic/energy 77.545 MeV
/run/beamOn {nevents}

/analysis/setFileName 100-20-3.6.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 3.700 mm
/PolarimeterStudies/dcelastic/energy 76.389 MeV
/run/beamOn {nevents}

/analysis/setFileName 100-20-3.8.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 3.900 mm
/PolarimeterStudies/dcelastic/energy 75.218 MeV
/run/beamOn {nevents}

/analysis/setFileName 100-20-4.0.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 4.100 mm
/PolarimeterStudies/dcelastic/energy 74.031 MeV
/run/beamOn {nevents}

/analysis/setFileName 100-20-4.2.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 4.300 mm
/PolarimeterStudies/dcelastic/energy 72.825 MeV
/run/beamOn {nevents}

/analysis/setFileName 100-20-4.4.root
/PolarimeterStudies/dcelastic/beamsize 5.002 5.002 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 4.500 mm
/PolarimeterStudies/dcelastic/energy 71.595 MeV
/run/beamOn {nevents}

/analysis/setFileName 100-20-4.6.root
/PolarimeterStudies/dcelastic/beamsize 5.002 5.002 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 4.700 mm
/PolarimeterStudies/dcelastic/energy 70.340 MeV
/run/beamOn {nevents}

/analysis/setFileName 100-20-4.8.root
/PolarimeterStudies/dcelastic/beamsize 5.002 5.002 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 4.900 mm
/PolarimeterStudies/dcelastic/energy 69.056 MeV
/run/beamOn {nevents}

/analysis/setFileName 100-20-5.0.root
/PolarimeterStudies/dcelastic/beamsize 5.002 5.002 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 5.100 mm
/PolarimeterStudies/dcelastic/energy 67.740 MeV
/run/beamOn {nevents}

/analysis/setFileName 100-20-5.2.root
/PolarimeterStudies/dcelastic/beamsize 5.003 5.003 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 5.300 mm
/PolarimeterStudies/dcelastic/energy 66.389 MeV
/run/beamOn {nevents}

/analysis/setFileName 100-20-5.4.root
/PolarimeterStudies/dcelastic/beamsize 5.003 5.003 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 5.500 mm
/PolarimeterStudies/dcelastic/energy 65.001 MeV
/run/beamOn {nevents}

/analysis/setFileName 100-20-5.6.root
/PolarimeterStudies/dcelastic/beamsize 5.003 5.003 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 5.700 mm
/PolarimeterStudies/dcelastic/energy 63.571 MeV
/run/beamOn {nevents}

/analysis/setFileName 100-20-5.8.root
/PolarimeterStudies/dcelastic/beamsize 5.004 5.004 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 5.900 mm
/PolarimeterStudies/dcelastic/energy 62.097 MeV
/run/beamOn {nevents}

/analysis/setFileName 100-20-6.0.root
/PolarimeterStudies/dcelastic/beamsize 5.004 5.004 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 6.100 mm
/PolarimeterStudies/dcelastic/energy 60.576 MeV
/run/beamOn {nevents}

/analysis/setFileName 100-20-6.2.root
/PolarimeterStudies/dcelastic/beamsize 5.005 5.005 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 6.300 mm
/PolarimeterStudies/dcelastic/energy 59.005 MeV
/run/beamOn {nevents}

/analysis/setFileName 100-20-6.4.root
/PolarimeterStudies/dcelastic/beamsize 5.005 5.005 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 6.500 mm
/PolarimeterStudies/dcelastic/energy 57.381 MeV
/run/beamOn {nevents}

/analysis/setFileName 100-20-6.6.root
/PolarimeterStudies/dcelastic/beamsize 5.006 5.006 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 6.700 mm
/PolarimeterStudies/dcelastic/energy 55.701 MeV
/run/beamOn {nevents}

/analysis/setFileName 100-20-6.8.root
/PolarimeterStudies/dcelastic/beamsize 5.006 5.006 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 6.900 mm
/PolarimeterStudies/dcelastic/energy 53.961 MeV
/run/beamOn {nevents}

