/PolarimeterStudies/target/z 10 mm 
/PolarimeterStudies/detector/update

/analysis/setFileName 150-10-0.root
/PolarimeterStudies/dcelastic/beamsize -0.065 -0.065 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 0.500 mm
/PolarimeterStudies/dcelastic/energy 160.708 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-1.root
/PolarimeterStudies/dcelastic/beamsize -0.034 -0.034 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 1.500 mm
/PolarimeterStudies/dcelastic/energy 151.955 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-2.root
/PolarimeterStudies/dcelastic/beamsize -0.001 -0.001 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 2.500 mm
/PolarimeterStudies/dcelastic/energy 144.130 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-3.root
/PolarimeterStudies/dcelastic/beamsize 0.034 0.034 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 3.500 mm
/PolarimeterStudies/dcelastic/energy 137.115 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-4.root
/PolarimeterStudies/dcelastic/beamsize 0.070 0.070 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 4.500 mm
/PolarimeterStudies/dcelastic/energy 130.788 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-5.root
/PolarimeterStudies/dcelastic/beamsize 0.108 0.108 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 5.500 mm
/PolarimeterStudies/dcelastic/energy 125.032 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-6.root
/PolarimeterStudies/dcelastic/beamsize 0.148 0.148 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 6.500 mm
/PolarimeterStudies/dcelastic/energy 119.724 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-7.root
/PolarimeterStudies/dcelastic/beamsize 0.189 0.189 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 7.500 mm
/PolarimeterStudies/dcelastic/energy 114.747 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-8.root
/PolarimeterStudies/dcelastic/beamsize 0.232 0.232 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 8.500 mm
/PolarimeterStudies/dcelastic/energy 109.979 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-9.root
/PolarimeterStudies/dcelastic/beamsize 0.277 0.277 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 9.500 mm
/PolarimeterStudies/dcelastic/energy 105.301 MeV
/run/beamOn {nevents}

