/PolarimeterStudies/target/z 10 mm 
/PolarimeterStudies/detector/update

/analysis/setFileName 150-10-0.0.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 0.100 mm
/PolarimeterStudies/dcelastic/energy 148.451 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-0.2.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 0.300 mm
/PolarimeterStudies/dcelastic/energy 147.570 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-0.4.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 0.500 mm
/PolarimeterStudies/dcelastic/energy 146.694 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-0.6.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 0.700 mm
/PolarimeterStudies/dcelastic/energy 145.822 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-0.8.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 0.900 mm
/PolarimeterStudies/dcelastic/energy 144.954 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-1.0.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 1.100 mm
/PolarimeterStudies/dcelastic/energy 144.091 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-1.2.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 1.300 mm
/PolarimeterStudies/dcelastic/energy 143.230 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-1.4.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 1.500 mm
/PolarimeterStudies/dcelastic/energy 142.373 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-1.6.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 1.700 mm
/PolarimeterStudies/dcelastic/energy 141.519 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-1.8.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 1.900 mm
/PolarimeterStudies/dcelastic/energy 140.668 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-2.0.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 2.100 mm
/PolarimeterStudies/dcelastic/energy 139.819 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-2.2.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 2.300 mm
/PolarimeterStudies/dcelastic/energy 138.972 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-2.4.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 2.500 mm
/PolarimeterStudies/dcelastic/energy 138.127 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-2.6.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 2.700 mm
/PolarimeterStudies/dcelastic/energy 137.283 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-2.8.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 2.900 mm
/PolarimeterStudies/dcelastic/energy 136.441 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-3.0.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 3.100 mm
/PolarimeterStudies/dcelastic/energy 135.599 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-3.2.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 3.300 mm
/PolarimeterStudies/dcelastic/energy 134.759 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-3.4.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 3.500 mm
/PolarimeterStudies/dcelastic/energy 133.918 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-3.6.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 3.700 mm
/PolarimeterStudies/dcelastic/energy 133.078 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-3.8.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 3.900 mm
/PolarimeterStudies/dcelastic/energy 132.237 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-4.0.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 4.100 mm
/PolarimeterStudies/dcelastic/energy 131.396 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-4.2.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 4.300 mm
/PolarimeterStudies/dcelastic/energy 130.554 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-4.4.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 4.500 mm
/PolarimeterStudies/dcelastic/energy 129.710 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-4.6.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 4.700 mm
/PolarimeterStudies/dcelastic/energy 128.866 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-4.8.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 4.900 mm
/PolarimeterStudies/dcelastic/energy 128.020 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-5.0.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 5.100 mm
/PolarimeterStudies/dcelastic/energy 127.171 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-5.2.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 5.300 mm
/PolarimeterStudies/dcelastic/energy 126.321 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-5.4.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 5.500 mm
/PolarimeterStudies/dcelastic/energy 125.467 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-5.6.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 5.700 mm
/PolarimeterStudies/dcelastic/energy 124.611 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-5.8.root
/PolarimeterStudies/dcelastic/beamsize 5.002 5.002 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 5.900 mm
/PolarimeterStudies/dcelastic/energy 123.752 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-6.0.root
/PolarimeterStudies/dcelastic/beamsize 5.002 5.002 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 6.100 mm
/PolarimeterStudies/dcelastic/energy 122.889 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-6.2.root
/PolarimeterStudies/dcelastic/beamsize 5.002 5.002 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 6.300 mm
/PolarimeterStudies/dcelastic/energy 122.023 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-6.4.root
/PolarimeterStudies/dcelastic/beamsize 5.002 5.002 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 6.500 mm
/PolarimeterStudies/dcelastic/energy 121.152 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-6.6.root
/PolarimeterStudies/dcelastic/beamsize 5.002 5.002 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 6.700 mm
/PolarimeterStudies/dcelastic/energy 120.278 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-6.8.root
/PolarimeterStudies/dcelastic/beamsize 5.002 5.002 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 6.900 mm
/PolarimeterStudies/dcelastic/energy 119.398 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-7.0.root
/PolarimeterStudies/dcelastic/beamsize 5.003 5.003 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 7.100 mm
/PolarimeterStudies/dcelastic/energy 118.514 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-7.2.root
/PolarimeterStudies/dcelastic/beamsize 5.003 5.003 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 7.300 mm
/PolarimeterStudies/dcelastic/energy 117.624 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-7.4.root
/PolarimeterStudies/dcelastic/beamsize 5.003 5.003 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 7.500 mm
/PolarimeterStudies/dcelastic/energy 116.729 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-7.6.root
/PolarimeterStudies/dcelastic/beamsize 5.003 5.003 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 7.700 mm
/PolarimeterStudies/dcelastic/energy 115.828 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-7.8.root
/PolarimeterStudies/dcelastic/beamsize 5.004 5.004 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 7.900 mm
/PolarimeterStudies/dcelastic/energy 114.921 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-8.0.root
/PolarimeterStudies/dcelastic/beamsize 5.004 5.004 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 8.100 mm
/PolarimeterStudies/dcelastic/energy 114.008 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-8.2.root
/PolarimeterStudies/dcelastic/beamsize 5.004 5.004 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 8.300 mm
/PolarimeterStudies/dcelastic/energy 113.088 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-8.4.root
/PolarimeterStudies/dcelastic/beamsize 5.005 5.005 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 8.500 mm
/PolarimeterStudies/dcelastic/energy 112.161 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-8.6.root
/PolarimeterStudies/dcelastic/beamsize 5.005 5.005 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 8.700 mm
/PolarimeterStudies/dcelastic/energy 111.227 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-8.8.root
/PolarimeterStudies/dcelastic/beamsize 5.005 5.005 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 8.900 mm
/PolarimeterStudies/dcelastic/energy 110.285 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-9.0.root
/PolarimeterStudies/dcelastic/beamsize 5.006 5.006 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 9.100 mm
/PolarimeterStudies/dcelastic/energy 109.336 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-9.2.root
/PolarimeterStudies/dcelastic/beamsize 5.006 5.006 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 9.300 mm
/PolarimeterStudies/dcelastic/energy 108.378 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-9.4.root
/PolarimeterStudies/dcelastic/beamsize 5.006 5.006 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 9.500 mm
/PolarimeterStudies/dcelastic/energy 107.412 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-9.6.root
/PolarimeterStudies/dcelastic/beamsize 5.007 5.007 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 9.700 mm
/PolarimeterStudies/dcelastic/energy 106.437 MeV
/run/beamOn {nevents}

/analysis/setFileName 150-10-9.8.root
/PolarimeterStudies/dcelastic/beamsize 5.007 5.007 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 9.900 mm
/PolarimeterStudies/dcelastic/energy 105.453 MeV
/run/beamOn {nevents}

