/PolarimeterStudies/target/z 10 mm 
/PolarimeterStudies/detector/update

/analysis/setFileName 200-10-0.root
/PolarimeterStudies/dcelastic/beamsize -0.019 -0.019 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 0.500 mm
/PolarimeterStudies/dcelastic/energy 206.567 MeV
/run/beamOn {nevents}

/analysis/setFileName 200-10-1.root
/PolarimeterStudies/dcelastic/beamsize -0.001 -0.001 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 1.500 mm
/PolarimeterStudies/dcelastic/energy 200.870 MeV
/run/beamOn {nevents}

/analysis/setFileName 200-10-2.root
/PolarimeterStudies/dcelastic/beamsize 0.019 0.019 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 2.500 mm
/PolarimeterStudies/dcelastic/energy 195.501 MeV
/run/beamOn {nevents}

/analysis/setFileName 200-10-3.root
/PolarimeterStudies/dcelastic/beamsize 0.040 0.040 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 3.500 mm
/PolarimeterStudies/dcelastic/energy 190.433 MeV
/run/beamOn {nevents}

/analysis/setFileName 200-10-4.root
/PolarimeterStudies/dcelastic/beamsize 0.063 0.063 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 4.500 mm
/PolarimeterStudies/dcelastic/energy 185.638 MeV
/run/beamOn {nevents}

/analysis/setFileName 200-10-5.root
/PolarimeterStudies/dcelastic/beamsize 0.087 0.087 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 5.500 mm
/PolarimeterStudies/dcelastic/energy 181.088 MeV
/run/beamOn {nevents}

/analysis/setFileName 200-10-6.root
/PolarimeterStudies/dcelastic/beamsize 0.112 0.112 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 6.500 mm
/PolarimeterStudies/dcelastic/energy 176.756 MeV
/run/beamOn {nevents}

/analysis/setFileName 200-10-7.root
/PolarimeterStudies/dcelastic/beamsize 0.139 0.139 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 7.500 mm
/PolarimeterStudies/dcelastic/energy 172.614 MeV
/run/beamOn {nevents}

/analysis/setFileName 200-10-8.root
/PolarimeterStudies/dcelastic/beamsize 0.167 0.167 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 8.500 mm
/PolarimeterStudies/dcelastic/energy 168.633 MeV
/run/beamOn {nevents}

/analysis/setFileName 200-10-9.root
/PolarimeterStudies/dcelastic/beamsize 0.197 0.197 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 9.500 mm
/PolarimeterStudies/dcelastic/energy 164.787 MeV
/run/beamOn {nevents}

