/PolarimeterStudies/target/z 5 mm 
/PolarimeterStudies/detector/update

/analysis/setFileName 200-5-0.0.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 0.100 mm
/PolarimeterStudies/dcelastic/energy 198.326 MeV
/run/beamOn {nevents}

/analysis/setFileName 200-5-0.2.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 0.300 mm
/PolarimeterStudies/dcelastic/energy 197.676 MeV
/run/beamOn {nevents}

/analysis/setFileName 200-5-0.4.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 0.500 mm
/PolarimeterStudies/dcelastic/energy 197.026 MeV
/run/beamOn {nevents}

/analysis/setFileName 200-5-0.6.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 0.700 mm
/PolarimeterStudies/dcelastic/energy 196.376 MeV
/run/beamOn {nevents}

/analysis/setFileName 200-5-0.8.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 0.900 mm
/PolarimeterStudies/dcelastic/energy 195.725 MeV
/run/beamOn {nevents}

/analysis/setFileName 200-5-1.0.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 1.100 mm
/PolarimeterStudies/dcelastic/energy 195.074 MeV
/run/beamOn {nevents}

/analysis/setFileName 200-5-1.2.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 1.300 mm
/PolarimeterStudies/dcelastic/energy 194.422 MeV
/run/beamOn {nevents}

/analysis/setFileName 200-5-1.4.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 1.500 mm
/PolarimeterStudies/dcelastic/energy 193.769 MeV
/run/beamOn {nevents}

/analysis/setFileName 200-5-1.6.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 1.700 mm
/PolarimeterStudies/dcelastic/energy 193.116 MeV
/run/beamOn {nevents}

/analysis/setFileName 200-5-1.8.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 1.900 mm
/PolarimeterStudies/dcelastic/energy 192.463 MeV
/run/beamOn {nevents}

/analysis/setFileName 200-5-2.0.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 2.100 mm
/PolarimeterStudies/dcelastic/energy 191.808 MeV
/run/beamOn {nevents}

/analysis/setFileName 200-5-2.2.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 2.300 mm
/PolarimeterStudies/dcelastic/energy 191.153 MeV
/run/beamOn {nevents}

/analysis/setFileName 200-5-2.4.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 2.500 mm
/PolarimeterStudies/dcelastic/energy 190.498 MeV
/run/beamOn {nevents}

/analysis/setFileName 200-5-2.6.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 2.700 mm
/PolarimeterStudies/dcelastic/energy 189.841 MeV
/run/beamOn {nevents}

/analysis/setFileName 200-5-2.8.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 2.900 mm
/PolarimeterStudies/dcelastic/energy 189.184 MeV
/run/beamOn {nevents}

/analysis/setFileName 200-5-3.0.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 3.100 mm
/PolarimeterStudies/dcelastic/energy 188.525 MeV
/run/beamOn {nevents}

/analysis/setFileName 200-5-3.2.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 3.300 mm
/PolarimeterStudies/dcelastic/energy 187.866 MeV
/run/beamOn {nevents}

/analysis/setFileName 200-5-3.4.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 3.500 mm
/PolarimeterStudies/dcelastic/energy 187.206 MeV
/run/beamOn {nevents}

/analysis/setFileName 200-5-3.6.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 3.700 mm
/PolarimeterStudies/dcelastic/energy 186.545 MeV
/run/beamOn {nevents}

/analysis/setFileName 200-5-3.8.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 3.900 mm
/PolarimeterStudies/dcelastic/energy 185.882 MeV
/run/beamOn {nevents}

/analysis/setFileName 200-5-4.0.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 4.100 mm
/PolarimeterStudies/dcelastic/energy 185.219 MeV
/run/beamOn {nevents}

/analysis/setFileName 200-5-4.2.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 4.300 mm
/PolarimeterStudies/dcelastic/energy 184.555 MeV
/run/beamOn {nevents}

/analysis/setFileName 200-5-4.4.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 4.500 mm
/PolarimeterStudies/dcelastic/energy 183.889 MeV
/run/beamOn {nevents}

/analysis/setFileName 200-5-4.6.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 4.700 mm
/PolarimeterStudies/dcelastic/energy 183.222 MeV
/run/beamOn {nevents}

/analysis/setFileName 200-5-4.8.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 4.900 mm
/PolarimeterStudies/dcelastic/energy 182.554 MeV
/run/beamOn {nevents}

