/PolarimeterStudies/target/z 10 mm 
/PolarimeterStudies/detector/update

/analysis/setFileName 250-10-0.0.root
/PolarimeterStudies/dcelastic/beamsize 5.010 5.010 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 0.100 mm
/PolarimeterStudies/dcelastic/energy 248.454 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-10-0.2.root
/PolarimeterStudies/dcelastic/beamsize 5.012 5.012 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 0.300 mm
/PolarimeterStudies/dcelastic/energy 247.914 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-10-0.4.root
/PolarimeterStudies/dcelastic/beamsize 5.014 5.014 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 0.500 mm
/PolarimeterStudies/dcelastic/energy 247.373 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-10-0.6.root
/PolarimeterStudies/dcelastic/beamsize 5.013 5.013 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 0.700 mm
/PolarimeterStudies/dcelastic/energy 246.831 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-10-0.8.root
/PolarimeterStudies/dcelastic/beamsize 5.013 5.013 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 0.900 mm
/PolarimeterStudies/dcelastic/energy 246.289 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-10-1.0.root
/PolarimeterStudies/dcelastic/beamsize 5.012 5.012 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 1.100 mm
/PolarimeterStudies/dcelastic/energy 245.745 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-10-1.2.root
/PolarimeterStudies/dcelastic/beamsize 5.012 5.012 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 1.300 mm
/PolarimeterStudies/dcelastic/energy 245.202 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-10-1.4.root
/PolarimeterStudies/dcelastic/beamsize 5.011 5.011 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 1.500 mm
/PolarimeterStudies/dcelastic/energy 244.657 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-10-1.6.root
/PolarimeterStudies/dcelastic/beamsize 5.007 5.007 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 1.700 mm
/PolarimeterStudies/dcelastic/energy 244.112 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-10-1.8.root
/PolarimeterStudies/dcelastic/beamsize 5.002 5.002 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 1.900 mm
/PolarimeterStudies/dcelastic/energy 243.565 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-10-2.0.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 2.100 mm
/PolarimeterStudies/dcelastic/energy 243.018 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-10-2.2.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 2.300 mm
/PolarimeterStudies/dcelastic/energy 242.471 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-10-2.4.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 2.500 mm
/PolarimeterStudies/dcelastic/energy 241.922 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-10-2.6.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 2.700 mm
/PolarimeterStudies/dcelastic/energy 241.373 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-10-2.8.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 2.900 mm
/PolarimeterStudies/dcelastic/energy 240.823 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-10-3.0.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 3.100 mm
/PolarimeterStudies/dcelastic/energy 240.272 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-10-3.2.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 3.300 mm
/PolarimeterStudies/dcelastic/energy 239.721 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-10-3.4.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 3.500 mm
/PolarimeterStudies/dcelastic/energy 239.168 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-10-3.6.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 3.700 mm
/PolarimeterStudies/dcelastic/energy 238.615 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-10-3.8.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 3.900 mm
/PolarimeterStudies/dcelastic/energy 238.061 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-10-4.0.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 4.100 mm
/PolarimeterStudies/dcelastic/energy 237.506 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-10-4.2.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 4.300 mm
/PolarimeterStudies/dcelastic/energy 236.950 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-10-4.4.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 4.500 mm
/PolarimeterStudies/dcelastic/energy 236.393 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-10-4.6.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 4.700 mm
/PolarimeterStudies/dcelastic/energy 235.835 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-10-4.8.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 4.900 mm
/PolarimeterStudies/dcelastic/energy 235.277 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-10-5.0.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 5.100 mm
/PolarimeterStudies/dcelastic/energy 234.718 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-10-5.2.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 5.300 mm
/PolarimeterStudies/dcelastic/energy 234.157 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-10-5.4.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 5.500 mm
/PolarimeterStudies/dcelastic/energy 233.596 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-10-5.6.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 5.700 mm
/PolarimeterStudies/dcelastic/energy 233.034 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-10-5.8.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 5.900 mm
/PolarimeterStudies/dcelastic/energy 232.471 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-10-6.0.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 6.100 mm
/PolarimeterStudies/dcelastic/energy 231.907 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-10-6.2.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 6.300 mm
/PolarimeterStudies/dcelastic/energy 231.342 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-10-6.4.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 6.500 mm
/PolarimeterStudies/dcelastic/energy 230.777 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-10-6.6.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 6.700 mm
/PolarimeterStudies/dcelastic/energy 230.210 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-10-6.8.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 6.900 mm
/PolarimeterStudies/dcelastic/energy 229.642 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-10-7.0.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 7.100 mm
/PolarimeterStudies/dcelastic/energy 229.073 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-10-7.2.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 7.300 mm
/PolarimeterStudies/dcelastic/energy 228.504 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-10-7.4.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 7.500 mm
/PolarimeterStudies/dcelastic/energy 227.933 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-10-7.6.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 7.700 mm
/PolarimeterStudies/dcelastic/energy 227.362 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-10-7.8.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 7.900 mm
/PolarimeterStudies/dcelastic/energy 226.789 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-10-8.0.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 8.100 mm
/PolarimeterStudies/dcelastic/energy 226.215 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-10-8.2.root
/PolarimeterStudies/dcelastic/beamsize 5.002 5.002 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 8.300 mm
/PolarimeterStudies/dcelastic/energy 225.641 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-10-8.4.root
/PolarimeterStudies/dcelastic/beamsize 5.002 5.002 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 8.500 mm
/PolarimeterStudies/dcelastic/energy 225.065 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-10-8.6.root
/PolarimeterStudies/dcelastic/beamsize 5.002 5.002 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 8.700 mm
/PolarimeterStudies/dcelastic/energy 224.488 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-10-8.8.root
/PolarimeterStudies/dcelastic/beamsize 5.002 5.002 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 8.900 mm
/PolarimeterStudies/dcelastic/energy 223.910 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-10-9.0.root
/PolarimeterStudies/dcelastic/beamsize 5.002 5.002 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 9.100 mm
/PolarimeterStudies/dcelastic/energy 223.332 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-10-9.2.root
/PolarimeterStudies/dcelastic/beamsize 5.002 5.002 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 9.300 mm
/PolarimeterStudies/dcelastic/energy 222.752 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-10-9.4.root
/PolarimeterStudies/dcelastic/beamsize 5.002 5.002 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 9.500 mm
/PolarimeterStudies/dcelastic/energy 222.171 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-10-9.6.root
/PolarimeterStudies/dcelastic/beamsize 5.002 5.002 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 9.700 mm
/PolarimeterStudies/dcelastic/energy 221.589 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-10-9.8.root
/PolarimeterStudies/dcelastic/beamsize 5.003 5.003 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 9.900 mm
/PolarimeterStudies/dcelastic/energy 221.006 MeV
/run/beamOn {nevents}

