/PolarimeterStudies/target/z 20 mm 
/PolarimeterStudies/detector/update

/analysis/setFileName 250-20-0.0.root
/PolarimeterStudies/dcelastic/beamsize 5.010 5.010 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 0.100 mm
/PolarimeterStudies/dcelastic/energy 248.454 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-0.2.root
/PolarimeterStudies/dcelastic/beamsize 5.012 5.012 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 0.300 mm
/PolarimeterStudies/dcelastic/energy 247.914 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-0.4.root
/PolarimeterStudies/dcelastic/beamsize 5.014 5.014 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 0.500 mm
/PolarimeterStudies/dcelastic/energy 247.373 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-0.6.root
/PolarimeterStudies/dcelastic/beamsize 5.013 5.013 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 0.700 mm
/PolarimeterStudies/dcelastic/energy 246.831 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-0.8.root
/PolarimeterStudies/dcelastic/beamsize 5.013 5.013 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 0.900 mm
/PolarimeterStudies/dcelastic/energy 246.289 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-1.0.root
/PolarimeterStudies/dcelastic/beamsize 5.012 5.012 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 1.100 mm
/PolarimeterStudies/dcelastic/energy 245.745 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-1.2.root
/PolarimeterStudies/dcelastic/beamsize 5.012 5.012 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 1.300 mm
/PolarimeterStudies/dcelastic/energy 245.202 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-1.4.root
/PolarimeterStudies/dcelastic/beamsize 5.011 5.011 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 1.500 mm
/PolarimeterStudies/dcelastic/energy 244.657 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-1.6.root
/PolarimeterStudies/dcelastic/beamsize 5.007 5.007 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 1.700 mm
/PolarimeterStudies/dcelastic/energy 244.112 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-1.8.root
/PolarimeterStudies/dcelastic/beamsize 5.002 5.002 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 1.900 mm
/PolarimeterStudies/dcelastic/energy 243.565 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-2.0.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 2.100 mm
/PolarimeterStudies/dcelastic/energy 243.018 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-2.2.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 2.300 mm
/PolarimeterStudies/dcelastic/energy 242.471 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-2.4.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 2.500 mm
/PolarimeterStudies/dcelastic/energy 241.922 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-2.6.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 2.700 mm
/PolarimeterStudies/dcelastic/energy 241.373 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-2.8.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 2.900 mm
/PolarimeterStudies/dcelastic/energy 240.823 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-3.0.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 3.100 mm
/PolarimeterStudies/dcelastic/energy 240.272 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-3.2.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 3.300 mm
/PolarimeterStudies/dcelastic/energy 239.721 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-3.4.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 3.500 mm
/PolarimeterStudies/dcelastic/energy 239.168 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-3.6.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 3.700 mm
/PolarimeterStudies/dcelastic/energy 238.615 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-3.8.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 3.900 mm
/PolarimeterStudies/dcelastic/energy 238.061 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-4.0.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 4.100 mm
/PolarimeterStudies/dcelastic/energy 237.506 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-4.2.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 4.300 mm
/PolarimeterStudies/dcelastic/energy 236.950 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-4.4.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 4.500 mm
/PolarimeterStudies/dcelastic/energy 236.393 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-4.6.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 4.700 mm
/PolarimeterStudies/dcelastic/energy 235.835 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-4.8.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 4.900 mm
/PolarimeterStudies/dcelastic/energy 235.277 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-5.0.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 5.100 mm
/PolarimeterStudies/dcelastic/energy 234.718 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-5.2.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 5.300 mm
/PolarimeterStudies/dcelastic/energy 234.157 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-5.4.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 5.500 mm
/PolarimeterStudies/dcelastic/energy 233.596 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-5.6.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 5.700 mm
/PolarimeterStudies/dcelastic/energy 233.034 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-5.8.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 5.900 mm
/PolarimeterStudies/dcelastic/energy 232.471 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-6.0.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 6.100 mm
/PolarimeterStudies/dcelastic/energy 231.907 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-6.2.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 6.300 mm
/PolarimeterStudies/dcelastic/energy 231.342 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-6.4.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 6.500 mm
/PolarimeterStudies/dcelastic/energy 230.777 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-6.6.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 6.700 mm
/PolarimeterStudies/dcelastic/energy 230.210 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-6.8.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 6.900 mm
/PolarimeterStudies/dcelastic/energy 229.642 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-7.0.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 7.100 mm
/PolarimeterStudies/dcelastic/energy 229.073 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-7.2.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 7.300 mm
/PolarimeterStudies/dcelastic/energy 228.504 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-7.4.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 7.500 mm
/PolarimeterStudies/dcelastic/energy 227.933 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-7.6.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 7.700 mm
/PolarimeterStudies/dcelastic/energy 227.362 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-7.8.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 7.900 mm
/PolarimeterStudies/dcelastic/energy 226.789 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-8.0.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 8.100 mm
/PolarimeterStudies/dcelastic/energy 226.215 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-8.2.root
/PolarimeterStudies/dcelastic/beamsize 5.002 5.002 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 8.300 mm
/PolarimeterStudies/dcelastic/energy 225.641 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-8.4.root
/PolarimeterStudies/dcelastic/beamsize 5.002 5.002 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 8.500 mm
/PolarimeterStudies/dcelastic/energy 225.065 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-8.6.root
/PolarimeterStudies/dcelastic/beamsize 5.002 5.002 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 8.700 mm
/PolarimeterStudies/dcelastic/energy 224.488 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-8.8.root
/PolarimeterStudies/dcelastic/beamsize 5.002 5.002 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 8.900 mm
/PolarimeterStudies/dcelastic/energy 223.910 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-9.0.root
/PolarimeterStudies/dcelastic/beamsize 5.002 5.002 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 9.100 mm
/PolarimeterStudies/dcelastic/energy 223.332 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-9.2.root
/PolarimeterStudies/dcelastic/beamsize 5.002 5.002 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 9.300 mm
/PolarimeterStudies/dcelastic/energy 222.752 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-9.4.root
/PolarimeterStudies/dcelastic/beamsize 5.002 5.002 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 9.500 mm
/PolarimeterStudies/dcelastic/energy 222.171 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-9.6.root
/PolarimeterStudies/dcelastic/beamsize 5.002 5.002 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 9.700 mm
/PolarimeterStudies/dcelastic/energy 221.589 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-9.8.root
/PolarimeterStudies/dcelastic/beamsize 5.003 5.003 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 9.900 mm
/PolarimeterStudies/dcelastic/energy 221.006 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-10.0.root
/PolarimeterStudies/dcelastic/beamsize 5.003 5.003 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 10.100 mm
/PolarimeterStudies/dcelastic/energy 220.421 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-10.2.root
/PolarimeterStudies/dcelastic/beamsize 5.003 5.003 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 10.300 mm
/PolarimeterStudies/dcelastic/energy 219.836 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-10.4.root
/PolarimeterStudies/dcelastic/beamsize 5.003 5.003 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 10.500 mm
/PolarimeterStudies/dcelastic/energy 219.250 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-10.6.root
/PolarimeterStudies/dcelastic/beamsize 5.003 5.003 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 10.700 mm
/PolarimeterStudies/dcelastic/energy 218.662 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-10.8.root
/PolarimeterStudies/dcelastic/beamsize 5.003 5.003 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 10.900 mm
/PolarimeterStudies/dcelastic/energy 218.073 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-11.0.root
/PolarimeterStudies/dcelastic/beamsize 5.004 5.004 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 11.100 mm
/PolarimeterStudies/dcelastic/energy 217.484 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-11.2.root
/PolarimeterStudies/dcelastic/beamsize 5.004 5.004 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 11.300 mm
/PolarimeterStudies/dcelastic/energy 216.893 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-11.4.root
/PolarimeterStudies/dcelastic/beamsize 5.004 5.004 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 11.500 mm
/PolarimeterStudies/dcelastic/energy 216.301 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-11.6.root
/PolarimeterStudies/dcelastic/beamsize 5.004 5.004 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 11.700 mm
/PolarimeterStudies/dcelastic/energy 215.707 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-11.8.root
/PolarimeterStudies/dcelastic/beamsize 5.004 5.004 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 11.900 mm
/PolarimeterStudies/dcelastic/energy 215.113 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-12.0.root
/PolarimeterStudies/dcelastic/beamsize 5.005 5.005 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 12.100 mm
/PolarimeterStudies/dcelastic/energy 214.517 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-12.2.root
/PolarimeterStudies/dcelastic/beamsize 5.005 5.005 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 12.300 mm
/PolarimeterStudies/dcelastic/energy 213.921 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-12.4.root
/PolarimeterStudies/dcelastic/beamsize 5.005 5.005 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 12.500 mm
/PolarimeterStudies/dcelastic/energy 213.323 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-12.6.root
/PolarimeterStudies/dcelastic/beamsize 5.005 5.005 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 12.700 mm
/PolarimeterStudies/dcelastic/energy 212.723 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-12.8.root
/PolarimeterStudies/dcelastic/beamsize 5.006 5.006 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 12.900 mm
/PolarimeterStudies/dcelastic/energy 212.123 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-13.0.root
/PolarimeterStudies/dcelastic/beamsize 5.006 5.006 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 13.100 mm
/PolarimeterStudies/dcelastic/energy 211.521 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-13.2.root
/PolarimeterStudies/dcelastic/beamsize 5.006 5.006 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 13.300 mm
/PolarimeterStudies/dcelastic/energy 210.919 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-13.4.root
/PolarimeterStudies/dcelastic/beamsize 5.006 5.006 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 13.500 mm
/PolarimeterStudies/dcelastic/energy 210.315 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-13.6.root
/PolarimeterStudies/dcelastic/beamsize 5.007 5.007 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 13.700 mm
/PolarimeterStudies/dcelastic/energy 209.709 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-13.8.root
/PolarimeterStudies/dcelastic/beamsize 5.007 5.007 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 13.900 mm
/PolarimeterStudies/dcelastic/energy 209.103 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-14.0.root
/PolarimeterStudies/dcelastic/beamsize 5.007 5.007 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 14.100 mm
/PolarimeterStudies/dcelastic/energy 208.495 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-14.2.root
/PolarimeterStudies/dcelastic/beamsize 5.008 5.008 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 14.300 mm
/PolarimeterStudies/dcelastic/energy 207.886 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-14.4.root
/PolarimeterStudies/dcelastic/beamsize 5.008 5.008 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 14.500 mm
/PolarimeterStudies/dcelastic/energy 207.275 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-14.6.root
/PolarimeterStudies/dcelastic/beamsize 5.008 5.008 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 14.700 mm
/PolarimeterStudies/dcelastic/energy 206.664 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-14.8.root
/PolarimeterStudies/dcelastic/beamsize 5.009 5.009 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 14.900 mm
/PolarimeterStudies/dcelastic/energy 206.051 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-15.0.root
/PolarimeterStudies/dcelastic/beamsize 5.009 5.009 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 15.100 mm
/PolarimeterStudies/dcelastic/energy 205.437 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-15.2.root
/PolarimeterStudies/dcelastic/beamsize 5.009 5.009 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 15.300 mm
/PolarimeterStudies/dcelastic/energy 204.821 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-15.4.root
/PolarimeterStudies/dcelastic/beamsize 5.010 5.010 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 15.500 mm
/PolarimeterStudies/dcelastic/energy 204.204 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-15.6.root
/PolarimeterStudies/dcelastic/beamsize 5.010 5.010 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 15.700 mm
/PolarimeterStudies/dcelastic/energy 203.586 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-15.8.root
/PolarimeterStudies/dcelastic/beamsize 5.010 5.010 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 15.900 mm
/PolarimeterStudies/dcelastic/energy 202.967 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-16.0.root
/PolarimeterStudies/dcelastic/beamsize 5.011 5.011 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 16.100 mm
/PolarimeterStudies/dcelastic/energy 202.346 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-16.2.root
/PolarimeterStudies/dcelastic/beamsize 5.011 5.011 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 16.300 mm
/PolarimeterStudies/dcelastic/energy 201.724 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-16.4.root
/PolarimeterStudies/dcelastic/beamsize 5.012 5.012 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 16.500 mm
/PolarimeterStudies/dcelastic/energy 201.100 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-16.6.root
/PolarimeterStudies/dcelastic/beamsize 5.012 5.012 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 16.700 mm
/PolarimeterStudies/dcelastic/energy 200.475 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-16.8.root
/PolarimeterStudies/dcelastic/beamsize 5.013 5.013 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 16.900 mm
/PolarimeterStudies/dcelastic/energy 199.849 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-17.0.root
/PolarimeterStudies/dcelastic/beamsize 5.013 5.013 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 17.100 mm
/PolarimeterStudies/dcelastic/energy 199.221 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-17.2.root
/PolarimeterStudies/dcelastic/beamsize 5.013 5.013 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 17.300 mm
/PolarimeterStudies/dcelastic/energy 198.592 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-17.4.root
/PolarimeterStudies/dcelastic/beamsize 5.014 5.014 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 17.500 mm
/PolarimeterStudies/dcelastic/energy 197.962 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-17.6.root
/PolarimeterStudies/dcelastic/beamsize 5.014 5.014 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 17.700 mm
/PolarimeterStudies/dcelastic/energy 197.330 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-17.8.root
/PolarimeterStudies/dcelastic/beamsize 5.015 5.015 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 17.900 mm
/PolarimeterStudies/dcelastic/energy 196.697 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-18.0.root
/PolarimeterStudies/dcelastic/beamsize 5.015 5.015 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 18.100 mm
/PolarimeterStudies/dcelastic/energy 196.062 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-18.2.root
/PolarimeterStudies/dcelastic/beamsize 5.016 5.016 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 18.300 mm
/PolarimeterStudies/dcelastic/energy 195.426 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-18.4.root
/PolarimeterStudies/dcelastic/beamsize 5.016 5.016 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 18.500 mm
/PolarimeterStudies/dcelastic/energy 194.788 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-18.6.root
/PolarimeterStudies/dcelastic/beamsize 5.017 5.017 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 18.700 mm
/PolarimeterStudies/dcelastic/energy 194.149 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-18.8.root
/PolarimeterStudies/dcelastic/beamsize 5.017 5.017 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 18.900 mm
/PolarimeterStudies/dcelastic/energy 193.509 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-19.0.root
/PolarimeterStudies/dcelastic/beamsize 5.018 5.018 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 19.100 mm
/PolarimeterStudies/dcelastic/energy 192.867 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-19.2.root
/PolarimeterStudies/dcelastic/beamsize 5.018 5.018 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 19.300 mm
/PolarimeterStudies/dcelastic/energy 192.223 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-19.4.root
/PolarimeterStudies/dcelastic/beamsize 5.019 5.019 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 19.500 mm
/PolarimeterStudies/dcelastic/energy 191.578 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-19.6.root
/PolarimeterStudies/dcelastic/beamsize 5.019 5.019 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 19.700 mm
/PolarimeterStudies/dcelastic/energy 190.932 MeV
/run/beamOn {nevents}

/analysis/setFileName 250-20-19.8.root
/PolarimeterStudies/dcelastic/beamsize 5.020 5.020 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 19.900 mm
/PolarimeterStudies/dcelastic/energy 190.284 MeV
/run/beamOn {nevents}

