/PolarimeterStudies/target/z 20 mm 
/PolarimeterStudies/detector/update

/analysis/setFileName 270-20-0.0.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 0.100 mm
/PolarimeterStudies/dcelastic/energy 268.584 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-0.2.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 0.300 mm
/PolarimeterStudies/dcelastic/energy 268.068 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-0.4.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 0.500 mm
/PolarimeterStudies/dcelastic/energy 267.552 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-0.6.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 0.700 mm
/PolarimeterStudies/dcelastic/energy 267.036 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-0.8.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 0.900 mm
/PolarimeterStudies/dcelastic/energy 266.519 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-1.0.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 1.100 mm
/PolarimeterStudies/dcelastic/energy 266.001 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-1.2.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 1.300 mm
/PolarimeterStudies/dcelastic/energy 265.484 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-1.4.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 1.500 mm
/PolarimeterStudies/dcelastic/energy 264.965 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-1.6.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 1.700 mm
/PolarimeterStudies/dcelastic/energy 264.447 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-1.8.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 1.900 mm
/PolarimeterStudies/dcelastic/energy 263.928 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-2.0.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 2.100 mm
/PolarimeterStudies/dcelastic/energy 263.408 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-2.2.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 2.300 mm
/PolarimeterStudies/dcelastic/energy 262.888 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-2.4.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 2.500 mm
/PolarimeterStudies/dcelastic/energy 262.368 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-2.6.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 2.700 mm
/PolarimeterStudies/dcelastic/energy 261.847 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-2.8.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 2.900 mm
/PolarimeterStudies/dcelastic/energy 261.325 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-3.0.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 3.100 mm
/PolarimeterStudies/dcelastic/energy 260.803 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-3.2.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 3.300 mm
/PolarimeterStudies/dcelastic/energy 260.280 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-3.4.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 3.500 mm
/PolarimeterStudies/dcelastic/energy 259.757 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-3.6.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 3.700 mm
/PolarimeterStudies/dcelastic/energy 259.234 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-3.8.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 3.900 mm
/PolarimeterStudies/dcelastic/energy 258.709 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-4.0.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 4.100 mm
/PolarimeterStudies/dcelastic/energy 258.185 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-4.2.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 4.300 mm
/PolarimeterStudies/dcelastic/energy 257.659 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-4.4.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 4.500 mm
/PolarimeterStudies/dcelastic/energy 257.133 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-4.6.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 4.700 mm
/PolarimeterStudies/dcelastic/energy 256.607 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-4.8.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 4.900 mm
/PolarimeterStudies/dcelastic/energy 256.080 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-5.0.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 5.100 mm
/PolarimeterStudies/dcelastic/energy 255.552 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-5.2.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 5.300 mm
/PolarimeterStudies/dcelastic/energy 255.023 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-5.4.root
/PolarimeterStudies/dcelastic/beamsize 5.000 5.000 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 5.500 mm
/PolarimeterStudies/dcelastic/energy 254.494 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-5.6.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 5.700 mm
/PolarimeterStudies/dcelastic/energy 253.965 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-5.8.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 5.900 mm
/PolarimeterStudies/dcelastic/energy 253.434 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-6.0.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 6.100 mm
/PolarimeterStudies/dcelastic/energy 252.903 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-6.2.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 6.300 mm
/PolarimeterStudies/dcelastic/energy 252.371 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-6.4.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 6.500 mm
/PolarimeterStudies/dcelastic/energy 251.839 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-6.6.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 6.700 mm
/PolarimeterStudies/dcelastic/energy 251.306 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-6.8.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 6.900 mm
/PolarimeterStudies/dcelastic/energy 250.772 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-7.0.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 7.100 mm
/PolarimeterStudies/dcelastic/energy 250.237 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-7.2.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 7.300 mm
/PolarimeterStudies/dcelastic/energy 249.702 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-7.4.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 7.500 mm
/PolarimeterStudies/dcelastic/energy 249.166 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-7.6.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 7.700 mm
/PolarimeterStudies/dcelastic/energy 248.629 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-7.8.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 7.900 mm
/PolarimeterStudies/dcelastic/energy 248.092 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-8.0.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 8.100 mm
/PolarimeterStudies/dcelastic/energy 247.553 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-8.2.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 8.300 mm
/PolarimeterStudies/dcelastic/energy 247.014 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-8.4.root
/PolarimeterStudies/dcelastic/beamsize 5.001 5.001 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 8.500 mm
/PolarimeterStudies/dcelastic/energy 246.474 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-8.6.root
/PolarimeterStudies/dcelastic/beamsize 5.002 5.002 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 8.700 mm
/PolarimeterStudies/dcelastic/energy 245.934 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-8.8.root
/PolarimeterStudies/dcelastic/beamsize 5.002 5.002 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 8.900 mm
/PolarimeterStudies/dcelastic/energy 245.392 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-9.0.root
/PolarimeterStudies/dcelastic/beamsize 5.002 5.002 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 9.100 mm
/PolarimeterStudies/dcelastic/energy 244.850 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-9.2.root
/PolarimeterStudies/dcelastic/beamsize 5.002 5.002 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 9.300 mm
/PolarimeterStudies/dcelastic/energy 244.306 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-9.4.root
/PolarimeterStudies/dcelastic/beamsize 5.002 5.002 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 9.500 mm
/PolarimeterStudies/dcelastic/energy 243.762 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-9.6.root
/PolarimeterStudies/dcelastic/beamsize 5.002 5.002 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 9.700 mm
/PolarimeterStudies/dcelastic/energy 243.217 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-9.8.root
/PolarimeterStudies/dcelastic/beamsize 5.002 5.002 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 9.900 mm
/PolarimeterStudies/dcelastic/energy 242.672 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-10.0.root
/PolarimeterStudies/dcelastic/beamsize 5.002 5.002 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 10.100 mm
/PolarimeterStudies/dcelastic/energy 242.125 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-10.2.root
/PolarimeterStudies/dcelastic/beamsize 5.003 5.003 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 10.300 mm
/PolarimeterStudies/dcelastic/energy 241.577 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-10.4.root
/PolarimeterStudies/dcelastic/beamsize 5.003 5.003 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 10.500 mm
/PolarimeterStudies/dcelastic/energy 241.029 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-10.6.root
/PolarimeterStudies/dcelastic/beamsize 5.003 5.003 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 10.700 mm
/PolarimeterStudies/dcelastic/energy 240.480 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-10.8.root
/PolarimeterStudies/dcelastic/beamsize 5.003 5.003 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 10.900 mm
/PolarimeterStudies/dcelastic/energy 239.929 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-11.0.root
/PolarimeterStudies/dcelastic/beamsize 5.003 5.003 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 11.100 mm
/PolarimeterStudies/dcelastic/energy 239.378 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-11.2.root
/PolarimeterStudies/dcelastic/beamsize 5.003 5.003 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 11.300 mm
/PolarimeterStudies/dcelastic/energy 238.826 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-11.4.root
/PolarimeterStudies/dcelastic/beamsize 5.003 5.003 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 11.500 mm
/PolarimeterStudies/dcelastic/energy 238.273 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-11.6.root
/PolarimeterStudies/dcelastic/beamsize 5.004 5.004 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 11.700 mm
/PolarimeterStudies/dcelastic/energy 237.719 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-11.8.root
/PolarimeterStudies/dcelastic/beamsize 5.004 5.004 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 11.900 mm
/PolarimeterStudies/dcelastic/energy 237.164 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-12.0.root
/PolarimeterStudies/dcelastic/beamsize 5.004 5.004 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 12.100 mm
/PolarimeterStudies/dcelastic/energy 236.608 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-12.2.root
/PolarimeterStudies/dcelastic/beamsize 5.004 5.004 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 12.300 mm
/PolarimeterStudies/dcelastic/energy 236.050 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-12.4.root
/PolarimeterStudies/dcelastic/beamsize 5.005 5.005 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 12.500 mm
/PolarimeterStudies/dcelastic/energy 235.492 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-12.6.root
/PolarimeterStudies/dcelastic/beamsize 5.005 5.005 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 12.700 mm
/PolarimeterStudies/dcelastic/energy 234.933 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-12.8.root
/PolarimeterStudies/dcelastic/beamsize 5.005 5.005 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 12.900 mm
/PolarimeterStudies/dcelastic/energy 234.373 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-13.0.root
/PolarimeterStudies/dcelastic/beamsize 5.005 5.005 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 13.100 mm
/PolarimeterStudies/dcelastic/energy 233.812 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-13.2.root
/PolarimeterStudies/dcelastic/beamsize 5.005 5.005 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 13.300 mm
/PolarimeterStudies/dcelastic/energy 233.250 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-13.4.root
/PolarimeterStudies/dcelastic/beamsize 5.006 5.006 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 13.500 mm
/PolarimeterStudies/dcelastic/energy 232.687 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-13.6.root
/PolarimeterStudies/dcelastic/beamsize 5.006 5.006 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 13.700 mm
/PolarimeterStudies/dcelastic/energy 232.123 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-13.8.root
/PolarimeterStudies/dcelastic/beamsize 5.006 5.006 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 13.900 mm
/PolarimeterStudies/dcelastic/energy 231.557 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-14.0.root
/PolarimeterStudies/dcelastic/beamsize 5.006 5.006 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 14.100 mm
/PolarimeterStudies/dcelastic/energy 230.991 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-14.2.root
/PolarimeterStudies/dcelastic/beamsize 5.007 5.007 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 14.300 mm
/PolarimeterStudies/dcelastic/energy 230.423 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-14.4.root
/PolarimeterStudies/dcelastic/beamsize 5.007 5.007 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 14.500 mm
/PolarimeterStudies/dcelastic/energy 229.854 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-14.6.root
/PolarimeterStudies/dcelastic/beamsize 5.007 5.007 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 14.700 mm
/PolarimeterStudies/dcelastic/energy 229.285 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-14.8.root
/PolarimeterStudies/dcelastic/beamsize 5.007 5.007 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 14.900 mm
/PolarimeterStudies/dcelastic/energy 228.714 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-15.0.root
/PolarimeterStudies/dcelastic/beamsize 5.008 5.008 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 15.100 mm
/PolarimeterStudies/dcelastic/energy 228.142 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-15.2.root
/PolarimeterStudies/dcelastic/beamsize 5.008 5.008 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 15.300 mm
/PolarimeterStudies/dcelastic/energy 227.569 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-15.4.root
/PolarimeterStudies/dcelastic/beamsize 5.008 5.008 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 15.500 mm
/PolarimeterStudies/dcelastic/energy 226.994 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-15.6.root
/PolarimeterStudies/dcelastic/beamsize 5.009 5.009 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 15.700 mm
/PolarimeterStudies/dcelastic/energy 226.419 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-15.8.root
/PolarimeterStudies/dcelastic/beamsize 5.009 5.009 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 15.900 mm
/PolarimeterStudies/dcelastic/energy 225.842 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-16.0.root
/PolarimeterStudies/dcelastic/beamsize 5.009 5.009 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 16.100 mm
/PolarimeterStudies/dcelastic/energy 225.264 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-16.2.root
/PolarimeterStudies/dcelastic/beamsize 5.010 5.010 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 16.300 mm
/PolarimeterStudies/dcelastic/energy 224.685 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-16.4.root
/PolarimeterStudies/dcelastic/beamsize 5.010 5.010 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 16.500 mm
/PolarimeterStudies/dcelastic/energy 224.105 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-16.6.root
/PolarimeterStudies/dcelastic/beamsize 5.011 5.011 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 16.700 mm
/PolarimeterStudies/dcelastic/energy 223.523 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-16.8.root
/PolarimeterStudies/dcelastic/beamsize 5.011 5.011 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 16.900 mm
/PolarimeterStudies/dcelastic/energy 222.940 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-17.0.root
/PolarimeterStudies/dcelastic/beamsize 5.011 5.011 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 17.100 mm
/PolarimeterStudies/dcelastic/energy 222.356 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-17.2.root
/PolarimeterStudies/dcelastic/beamsize 5.012 5.012 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 17.300 mm
/PolarimeterStudies/dcelastic/energy 221.771 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-17.4.root
/PolarimeterStudies/dcelastic/beamsize 5.012 5.012 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 17.500 mm
/PolarimeterStudies/dcelastic/energy 221.185 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-17.6.root
/PolarimeterStudies/dcelastic/beamsize 5.013 5.013 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 17.700 mm
/PolarimeterStudies/dcelastic/energy 220.597 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-17.8.root
/PolarimeterStudies/dcelastic/beamsize 5.013 5.013 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 17.900 mm
/PolarimeterStudies/dcelastic/energy 220.008 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-18.0.root
/PolarimeterStudies/dcelastic/beamsize 5.014 5.014 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 18.100 mm
/PolarimeterStudies/dcelastic/energy 219.417 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-18.2.root
/PolarimeterStudies/dcelastic/beamsize 5.014 5.014 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 18.300 mm
/PolarimeterStudies/dcelastic/energy 218.826 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-18.4.root
/PolarimeterStudies/dcelastic/beamsize 5.014 5.014 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 18.500 mm
/PolarimeterStudies/dcelastic/energy 218.233 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-18.6.root
/PolarimeterStudies/dcelastic/beamsize 5.015 5.015 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 18.700 mm
/PolarimeterStudies/dcelastic/energy 217.638 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-18.8.root
/PolarimeterStudies/dcelastic/beamsize 5.015 5.015 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 18.900 mm
/PolarimeterStudies/dcelastic/energy 217.043 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-19.0.root
/PolarimeterStudies/dcelastic/beamsize 5.016 5.016 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 19.100 mm
/PolarimeterStudies/dcelastic/energy 216.446 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-19.2.root
/PolarimeterStudies/dcelastic/beamsize 5.016 5.016 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 19.300 mm
/PolarimeterStudies/dcelastic/energy 215.847 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-19.4.root
/PolarimeterStudies/dcelastic/beamsize 5.017 5.017 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 19.500 mm
/PolarimeterStudies/dcelastic/energy 215.248 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-19.6.root
/PolarimeterStudies/dcelastic/beamsize 5.017 5.017 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 19.700 mm
/PolarimeterStudies/dcelastic/energy 214.647 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-19.8.root
/PolarimeterStudies/dcelastic/beamsize 5.018 5.018 0.200 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 19.900 mm
/PolarimeterStudies/dcelastic/energy 214.044 MeV
/run/beamOn {nevents}

