/PolarimeterStudies/target/z 20 mm 
/PolarimeterStudies/detector/update

/analysis/setFileName 270-20-0.root
/PolarimeterStudies/dcelastic/beamsize -0.001 -0.001 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 0.500 mm
/PolarimeterStudies/dcelastic/energy 272.596 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-1.root
/PolarimeterStudies/dcelastic/beamsize 0.012 0.012 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 1.500 mm
/PolarimeterStudies/dcelastic/energy 269.010 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-2.root
/PolarimeterStudies/dcelastic/beamsize 0.025 0.025 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 2.500 mm
/PolarimeterStudies/dcelastic/energy 265.507 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-3.root
/PolarimeterStudies/dcelastic/beamsize 0.040 0.040 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 3.500 mm
/PolarimeterStudies/dcelastic/energy 262.083 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-4.root
/PolarimeterStudies/dcelastic/beamsize 0.056 0.056 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 4.500 mm
/PolarimeterStudies/dcelastic/energy 258.731 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-5.root
/PolarimeterStudies/dcelastic/beamsize 0.073 0.073 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 5.500 mm
/PolarimeterStudies/dcelastic/energy 255.447 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-6.root
/PolarimeterStudies/dcelastic/beamsize 0.091 0.091 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 6.500 mm
/PolarimeterStudies/dcelastic/energy 252.225 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-7.root
/PolarimeterStudies/dcelastic/beamsize 0.109 0.109 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 7.500 mm
/PolarimeterStudies/dcelastic/energy 249.061 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-8.root
/PolarimeterStudies/dcelastic/beamsize 0.129 0.129 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 8.500 mm
/PolarimeterStudies/dcelastic/energy 245.950 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-9.root
/PolarimeterStudies/dcelastic/beamsize 0.150 0.150 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 9.500 mm
/PolarimeterStudies/dcelastic/energy 242.886 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-10.root
/PolarimeterStudies/dcelastic/beamsize 0.172 0.172 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 10.500 mm
/PolarimeterStudies/dcelastic/energy 239.864 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-11.root
/PolarimeterStudies/dcelastic/beamsize 0.195 0.195 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 11.500 mm
/PolarimeterStudies/dcelastic/energy 236.880 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-12.root
/PolarimeterStudies/dcelastic/beamsize 0.220 0.220 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 12.500 mm
/PolarimeterStudies/dcelastic/energy 233.928 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-13.root
/PolarimeterStudies/dcelastic/beamsize 0.245 0.245 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 13.500 mm
/PolarimeterStudies/dcelastic/energy 231.003 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-14.root
/PolarimeterStudies/dcelastic/beamsize 0.271 0.271 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 14.500 mm
/PolarimeterStudies/dcelastic/energy 228.101 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-15.root
/PolarimeterStudies/dcelastic/beamsize 0.298 0.298 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 15.500 mm
/PolarimeterStudies/dcelastic/energy 225.215 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-16.root
/PolarimeterStudies/dcelastic/beamsize 0.327 0.327 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 16.500 mm
/PolarimeterStudies/dcelastic/energy 222.341 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-17.root
/PolarimeterStudies/dcelastic/beamsize 0.356 0.356 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 17.500 mm
/PolarimeterStudies/dcelastic/energy 219.475 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-18.root
/PolarimeterStudies/dcelastic/beamsize 0.386 0.386 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 18.500 mm
/PolarimeterStudies/dcelastic/energy 216.610 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-20-19.root
/PolarimeterStudies/dcelastic/beamsize 0.418 0.418 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 19.500 mm
/PolarimeterStudies/dcelastic/energy 213.741 MeV
/run/beamOn {nevents}

