/PolarimeterStudies/target/z 10 mm 
/PolarimeterStudies/detector/update

/analysis/setFileName 270-10-0.root
/PolarimeterStudies/dcelastic/beamsize -0.001 -0.001 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 0.500 mm
/PolarimeterStudies/dcelastic/energy 272.596 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-10-1.root
/PolarimeterStudies/dcelastic/beamsize 0.012 0.012 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 1.500 mm
/PolarimeterStudies/dcelastic/energy 269.010 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-10-2.root
/PolarimeterStudies/dcelastic/beamsize 0.025 0.025 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 2.500 mm
/PolarimeterStudies/dcelastic/energy 265.507 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-10-3.root
/PolarimeterStudies/dcelastic/beamsize 0.040 0.040 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 3.500 mm
/PolarimeterStudies/dcelastic/energy 262.083 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-10-4.root
/PolarimeterStudies/dcelastic/beamsize 0.056 0.056 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 4.500 mm
/PolarimeterStudies/dcelastic/energy 258.731 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-10-5.root
/PolarimeterStudies/dcelastic/beamsize 0.073 0.073 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 5.500 mm
/PolarimeterStudies/dcelastic/energy 255.447 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-10-6.root
/PolarimeterStudies/dcelastic/beamsize 0.091 0.091 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 6.500 mm
/PolarimeterStudies/dcelastic/energy 252.225 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-10-7.root
/PolarimeterStudies/dcelastic/beamsize 0.109 0.109 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 7.500 mm
/PolarimeterStudies/dcelastic/energy 249.061 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-10-8.root
/PolarimeterStudies/dcelastic/beamsize 0.129 0.129 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 8.500 mm
/PolarimeterStudies/dcelastic/energy 245.950 MeV
/run/beamOn {nevents}

/analysis/setFileName 270-10-9.root
/PolarimeterStudies/dcelastic/beamsize 0.150 0.150 1.000 mm
/PolarimeterStudies/dcelastic/beamposition 0.000 0.000 9.500 mm
/PolarimeterStudies/dcelastic/energy 242.886 MeV
/run/beamOn {nevents}

