#!/usr/bin/python
import ROOT
from math import hypot,acos,sin
ROOT.gStyle.SetOptStat(0000000000000)
infile=ROOT.TFile("run_0.root")
outfile=ROOT.TFile("histos.root","RECREATE")
outfile.cd()
gen=infile.Get("gen")
hEd=ROOT.TH1F("Ed","deuteron energy",300,0,300)
hTheta=ROOT.TH1F("theta","theta",180,0,180)
hEvsTheta=ROOT.TH2F("Ev vs theta","",90,0,180,150,0,300)
hXSec=ROOT.TH1F("xec","xsec",180,0,180)
for entry in gen:
    for part in gen.dcinelastic.particles:
        if part.id==1000010020:
            hEd.Fill(part.E)
            mom=hypot(part.pz,hypot(part.px,part.py))
            theta=180/3.1415*acos(part.pz/mom)
            hEd.Fill(part.E)
            hTheta.Fill(theta)
            hEvsTheta.Fill(theta,part.E)
            hXSec.Fill(theta,1/sin(3.1415/180.*theta))
hEd.GetXaxis().SetTitle("E_{d} [MeV]")
hEd.Scale(1./hEd.GetEntries())
c1=ROOT.TCanvas("_","_",1200,800) 
hEd.Draw()
c1.Print("ed.pdf")
hTheta.Draw()
c1.Print("theta.pdf")
hEvsTheta.GetXaxis().SetTitle("#Theta [deg]")
hEvsTheta.GetYaxis().SetTitle("E_{d} [MeV]")
hEvsTheta.SetTitle("^{12}C(d,d)^{12}C")
hEvsTheta.Draw("col")
c1.Print("EvsTheta.pdf")
c1.Print("EvsTheta.root")
hXSec.Draw()
c1.Print("xsec.pdf")
hEd.Write()
hXSec.Write()
hTheta.Write()
hEvsTheta.Write()
