/analysis/Enable
/PolarimeterStudies/detector/calolength 10 cm
/PolarimeterStudies/detector/calowidth 3 cm
/PolarimeterStudies/detector/update
/gun/particle deuteron
/gun/energy 270 MeV
/gun/direction 0 0 1
/gun/position 0 0 -10 cm
/control/alias 100 6.
/control/alias 150 15.
/control/alias 200 26.
/control/alias 250 40.
/control/alias 270 46.
/control/foreach scripts/efficiency-plastic-singlerun.mac Ekin "100 150 200 250 270"