/analysis/Enable
/analysis/setFileName protons_small_target.root
/PolarimeterStudies/detector/material G4_LYSO_SCINT
/PolarimeterStudies/detector/tgtThickness 2 cm
/PolarimeterStudies/detector/tgtWidth 2 cm
/PolarimeterStudies/detector/update
/gun/position 0 0 -10 cm
/gun/direction 0 0 1
/gun/particle proton
/gun/momentumAmp 701 MeV
/run/beamOn 100000
/PolarimeterStudies/detector/tgtThickness 5 cm
/PolarimeterStudies/detector/update
/analysis/setFileName protons_big_target.root
/run/beamOn 100000
