/analysis/Enable
/PolarimeterStudies/generator/setGenerator beam
/PolarimeterStudies/beam/position 0 0 -5 cm
/PolarimeterStudies/beam/spotsize 1 1 0 cm
/PolarimeterStudies/beam/xp 2.5 deg
/PolarimeterStudies/beam/yp 2.5 deg

/PolarimeterStudies/detector/right 0
/PolarimeterStudies/detector/armangle 0 deg
/PolarimeterStudies/detector/update
/control/foreach scripts/TestBeam2016BEffectiveSize-singlerun.mac Ekin "100 150 200 250 270"