/analysis/Enable
/analysis/setFileName muons.root
/PolarimeterStudies/generator/Mode 3
/PolarimeterStudies/generator/setGenerator muon
/gun/position 0 20 5 cm
/PolarimeterStudies/detector/calowidth 3 cm
/PolarimeterStudies/detector/calolength 10 cm
/PolarimeterStudies/detector/update
/PolarimeterStudies/muon/spotsize 1000 1000 0 mm
/PolarimeterStudies/muon/position 0 2000<0 50 mm
/run/beamOn 1000000