/PolarimeterStudies/detector/left 0
/PolarimeterStudies/detector/armangle 0
/PolarimeterStudies/detector/armlength 30 cm
/PolarimeterStudies/detector/target 0
/PolarimeterStudies/detector/triggerthickness 8 mm
/PolarimeterStudies/detector/calolength 20 cm
/PolarimeterStudies/TriggerR/SetType calo
/PolarimeterStudies/detector/update
/PolarimeterStudies/generator/setGenerator gps
/analysis/Enable
/analysis/setFileName deuteron.root
/gps/particle deuteron
/gps/position 0 0.15 0 cm
/gps/direction 0 0 1
/gps/ene/type Lin
/gps/ene/min 1 MeV
/gps/ene/max 300 MeV
/gps/ene/intercept 1
/gps/ene/gradient 0
/run/beamOn 50000
/analysis/setFileName proton.root
/gps/particle proton
/run/beamOn 50000