/analysis/Enable
/PolarimeterStudies/generator/setGenerator dcelastic
/PolarimeterStudies/dcelastic/energy 270 MeV
/PolarimeterStudies/dcelastic/beamspot 0 0 0 cm
/PolarimeterStudies/dcelastic/beamsize .5 .5 0 cm
/PolarimeterStudies/dcelastic/thetamin 3 deg

/PolarimeterStudies/detector/detector effective
/PolarimeterStudies/detector/armangle 5 deg
/PolarimeterStudies/detector/target 0
/PolarimeterStudies/detector/update
/control/foreach scripts/TestBeam2016BMaterialInfluence-singlerun.mac Ekin "100 150 200 250 270"