/PolarimeterStudies/detector/scenario isolation
/run/initialize
/jedi/elastic/theta_min 4.5 deg
/jedi/elastic/theta_max 14.5 deg
/analysis/Enable
/PolarimeterStudies/generator/setGenerator beam
/PolarimeterStudies/beam/form gaus
/PolarimeterStudies/beam/position 0 0 -75 cm
/PolarimeterStudies/beam/spotsize 2.5 3 0 mm
/PolarimeterStudies/detector/targetSizeXY 50 mm
/PolarimeterStudies/detector/angle_left 9 deg
/PolarimeterStudies/detector/angle_left 9.8 deg
/PolarimeterStudies/detector/trigger_thick_left 10 mm
/PolarimeterStudies/detector/trigger_thick_right 5 mm
/PolarimeterStudies/detector/aperture 38.8 mm
/control/alias thickness 5
/PolarimeterStudies/detector/update
/control/execute scripts/TestBeam2016BIsolation/material.mac

/control/alias material G4_GRAPHITE
/control/alias thickness 10
/control/execute scripts/TestBeam2016BIsolation/energy.mac