/PolarimeterStudies/detector/scenario isolation
/run/initialize
/jedi/elastic/theta_min 4 deg
#No small theta_max because it might cause crashes at small energies and we do not lose much efficiency anyway because the xsec is small
/jedi/elastic/theta_max 25 deg
/analysis/Enable
/gun/particle deuteron
/PolarimeterStudies/generator/setGenerator beam
/PolarimeterStudies/beam/form gaus
/PolarimeterStudies/beam/position 0 0 -75 cm
/PolarimeterStudies/beam/spotsize 2.5 3 0 mm
/PolarimeterStudies/detector/targetSizeXY 50 mm
/PolarimeterStudies/detector/nx 4
/PolarimeterStudies/detector/ny 3
/PolarimeterStudies/detector/angle_left 9.8 deg
/PolarimeterStudies/detector/angle_right 9 deg
/PolarimeterStudies/detector/trigger 1
/PolarimeterStudies/detector/trigger_thick_left 10 mm
/PolarimeterStudies/detector/trigger_thick_right 5 mm
/PolarimeterStudies/detector/aperture 38.8 mm
/PolarimeterStudies/Right/depth 3
/PolarimeterStudies/Left/depth 3
/control/alias thickness 5
/PolarimeterStudies/detector/update
/control/execute scripts/Testbeam2016bIsolation/material.mac

/control/alias material G4_GRAPHITE
/control/alias thickness 10
/control/execute scripts/Testbeam2016bIsolation/energy.mac