#
# This file permits to customize, with commands,
# the menu bar of the G4UIXm, G4UIQt, G4UIWin32 sessions.
# It has no effect with G4UIterminal.
#
# Process vis.mac (and draw geometry)
#
/control/execute vis.mac
#
# Add icons of general interest
#
/control/execute icons.mac
#
# File menu :
/gui/addMenu file File
/gui/addButton file Quit exit
#
# Run menu :
/gui/addMenu run Run
/gui/addButton run "beamOn 100" "/run/beamOn 100"
#/gui/addButton run run1 "/control/execute run1.mac"
#/gui/addButton run run2 "/control/execute run2.mac"
#
# Gun menu :
/gui/addMenu gun Gun
/gui/addButton gun "100 MeV"  "/gun/energy 100 MeV"
/gui/addButton gun "250 MeV"  "/gun/energy 250 MeV"
/gui/addButton gun "1 GeV"    "/gun/energy 1 GeV"
/gui/addButton gun "e-"       "/gun/particle e-"
/gui/addButton gun "mu-"      "/gun/particle mu-"
/gui/addButton gun "deuteron" "/gun/particle deuteron"
/gui/addButton gun "neutron"  "/gun/particle neutron"
/gui/addButton gun "proton"   "/gun/particle proton"
#

# Viewer menu :
/gui/addMenu viewer Viewer
/gui/addButton viewer "Set style surface" "/vis/viewer/set/style surface"
/gui/addButton viewer "Set style wireframe" "/vis/viewer/set/style wireframe"
/gui/addButton viewer "Refresh viewer" "/vis/viewer/refresh"
/gui/addButton viewer "Update viewer (interaction or end-of-file)" "/vis/viewer/update"
/gui/addButton viewer "Flush viewer (= refresh + update)" "/vis/viewer/flush"
/gui/addButton viewer "Update scene" "/vis/scene/notifyHandlers"
#
# User defined icon :
/gui/addIcon "Run beam on" user_icon "/run/beamOn 100" run.png 
